### ISSUE TITLE
[Improvement] http 메소드 개선

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/frog_mahjong_game#105]
### 개선 상세 정보
- 요청자 : @JokerTrickster 
- What : http 메소드 개선
- Why : restful하게 사용하기 위해서 개선
- How : 위키에 http 메소드에 대해서 정리 후 현재 구현된 기능들 검토 후 수정

### Tasks
- [ ] http 메소드 정리 위키 문서 등록
- [ ] 기능 검토 및 수정
- [ ] 테스트 코드 
- [ ] 테스트 및 dev 배포
