### ISSUE TITLE
[Feature] 방 유저 강퇴 api

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/frog_mahjong_game#130]
### 새로운 기능
- 요청자 :   @JokerTrickster 
- What :    방 유저 강퇴 api
- Why :  방장이 방안에 특정 유저 강퇴할 수 있는 api
- How :   
request
<pre>
 {
    userID int
    roomID int
 }
</pre>

### Tasks
- [ ] 방 유저 강퇴 시퀀스 다이어그램 작성
- [ ] 방 유저 강퇴 api 기능 구현
- [ ] 테스트 코드 작성
- [ ] dev 배포
