### ISSUE TITLE
[Improvement] 요청에 카드ID 하나만 사용하는 이벤트는 배열 제거

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/frog_mahjong_game#199]
### 개선 상세 정보
- 요청자 : @JokerTrickster 
- What : 요청에 카드ID 하나만 사용하는 이벤트는 배열 제거
- Why :  카드 ID 하나만 받으면 되는데 배열로 받아서 혼동을 야기할 수 있기 때문에 수정 필요
- How : IMPORT_SINGLE_CARD, DORA, LOAN 이벤트 수정

### Tasks
- [ ] IMPORT_SINGLE_CARD 이벤트 수정
- [ ] DORA 이벤트 수정
- [ ] LOAN 이벤트 수정
- [ ] 테스트
