### ISSUE TITLE
[Feature] db 스키마 생성

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/frog_mahjong_game#38]
### 새로운 기능
- 요청자 :   @RyanBreathings 
- What :  db 스키마 생성
- Why :  필요한 db 스키마 생성
- How :  유저, 방, 게임 정보에 대한 db 스키마 생성

### Tasks
- [ ] 유저 스키마 생성
- [ ] 게임 방 스키마 생성
- [ ] 게임 정보 스키마 생성
- [ ] 테스트

**Comment by JokerTrickster** [comment]
[db 스키마 er 다이어그램 문서 링크](https://app.diagrams.net/#G1smRemY5eIs2agfMoVdHPeyuGNXXIBF5Y#%7B%22pageId%22%3A%22R2lEEEUBdFMjLlhIrx00%22%7D)
