### ISSUE TITLE
[Feature] 방 목록 가져오기 api 

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/frog_mahjong_game#79]
### 새로운 기능
- 요청자 :   @JokerTrickster 
- What :   방 목록 가져오기 api 
- Why :  플레이어가 참여하기 위해
- How :  삭제되지 않은 방들을 모두 가져와서 리스트해준다. 페이지네이션 적용

요청 
<pre>
 { 
   page int,
   pageSize int
 }

</pre>

응답
<pre>
{ 
 rooms : [ 
   { 
    roomID int, 
    created int, 
    currentCount int,
    maxCount int,
    minCount int,
    name string,
    password string,
    state string,
    owner string
   }
   ...
 ],
 total int
}
</pre>

### Tasks
- [ ] 방 목록 가져오기 api
- [ ] 테스트 코드 작성
- [ ] 테스트 및 dev 배포
