### ISSUE TITLE
[Improvement] 방 생성시 roomID 응답 프로퍼티 추가

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/frog_mahjong_game#92]
### 개선 상세 정보
- 요청자 : @JokerTrickster 
- What : 방 생성시 roomID 응답 프로퍼티 추가
- Why : 방나가거나 roomID 필요할 때 사용하기 위해 쿠키에 저장
- How : 
방 생성 성공시 
응답
<pre>
{
 roomID int
}
</pre>

### Tasks
- [ ] 방 생성시 응답 프로퍼티 수정
- [ ] 테스트 코드 작성
- [ ] 테스트 및 dev 배포

**Comment by JokerTrickster** [comment]
방 생성, 방 조인시 룸ID 응답하도록 변경
