### ISSUE TITLE
[Improvement] 방 나가기시 방 현재 인원에 따라서 상태 변경

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/frog_mahjong_game#94]
### 개선 상세 정보
- 요청자 : @JokerTrickster 
- What : 방 나가기시 방 현재 인원에 따라서 상태 변경
- Why :  디비에서 삭제하거나 변경하기 위해
- How :  
현재 인원이 0 명이면 방 삭제
현재 인원이 1 명이면 남아 있는 유저를 방장으로 변경
방장이 나가면 들어간 유저 중 한명을 방장으로 변경

### Tasks
- [ ] 방 나가기 비즈니스 로직 변경 
- [ ] 테스트 코드 작성
- [ ] 테스트 및 dev 배포
